# Generated by Django 4.2.20 on 2025-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0002_alter_materialimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimage',
            name='image',
            field=models.TextField(),
        ),
    ]
