# Generated by Django 5.2 on 2025-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_alter_materialimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialimage',
            name='image',
            field=models.ImageField(upload_to='material_images/'),
        ),
    ]
