# Generated by Django 4.2.20 on 2025-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
